name: Doxygen documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen
        run: sudo apt-get install doxygen
      - name: Generate documentation
        run: doxygen Doxyfile
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: html
