name: Makefile CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        compiler:
          - gcc

    steps:
      - uses: actions/checkout@v3

      - name: Setup C/C++ and make
        uses: aminya/setup-cpp@v0.26.2
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build autotests
        run: make autotests

      - name: Build simulation
        run: make simulation

      - name: Build usb
        run: make usb
